export {
    switching,
    condition,
    delay,
    promiseSequence,
    promiseSettledSequence,
    tryRequest,
    macrotask,
    toggleArray,
    sortDescriptor,
    getPercentage,
    ratioRange,
    arrayToMap,
    ArrayOfObjects,
    SVG,
    IMG,
    FILE,
    generateString,
    SortDirection,
    includesAll,
    objectEntries,
    objectKeys,
    removeAt,
    Interval,
    animate
} from './utility';
